# Generated by Django 4.2.1 on 2024-03-16 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_language_specialities_lawyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='lawyer',
            name='specialities',
        ),
        migrations.RemoveField(
            model_name='lawyer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Lawyer',
        ),
        migrations.DeleteModel(
            name='Specialities',
        ),
    ]
