# Generated by Django 4.2.1 on 2024-03-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_lawyer_languages_remove_lawyer_specialities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_lawyer',
            field=models.BooleanField(default=False),
        ),
    ]
