# Generated by Django 4.2.1 on 2024-03-19 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mouhami_api', '0004_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
