# Generated by Django 4.2.1 on 2024-03-20 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mouhami_api', '0006_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviewer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='lawyer_id',
            new_name='lawyer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='booking',
        ),
    ]
