# Generated by Django 4.2.1 on 2024-03-20 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mouhami_api', '0007_rename_reviewer_id_review_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booked',
        ),
    ]
