# Generated by Django 4.2.1 on 2024-03-22 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mouhami_api', '0009_booked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
