# Generated by Django 4.2.1 on 2024-03-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouhami_api', '0012_review_date_review_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='state',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show'), ('IN_PROGRESS', 'In Progress')], default='REQUESTED', max_length=12),
        ),
    ]
